# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    
      
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Auto Assign Action
  # You may pin to the exact commit or the version.
  # uses: kentaro-m/auto-assign-action@50ee9a1818bde2eb93a948448994a9d414457e3a
      uses: kentaro-m/auto-assign-action@v1.2.0
      with:
    # A token for the repo
        repo-token: ${{ github.token }} # optional, default is ${{ github.token }}
    # A path for the auto-assign configuration
        configuration-path: .github/auto_assign.yml # optional, default is .github/auto_assign.yml
